# Generated by Django 3.0.1 on 2021-12-07 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('auteur', models.CharField(max_length=60)),
                ('prix', models.FloatField(default=0)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
